runtime: ruby20

build: |
  {{ parent }}

run: |
  source .env

  if [ -z "$PORT" ]
  then
    export PORT=5000
  fi

  thin start -R config.ru -p $PORT

rake: |
  source .env
  rake $ROCK_ARGV

test: |
  source .env

  {{ parent }}
